import { useEffect,useState } from "react";
import { Check, ClipboardCheck, RefreshCw } from "lucide-react";
import StatusBadge from "../components/StatusBadge";
import { api } from "../services/api";
export default function Alerts({notify}) {
 const [items,setItems]=useState([]); const load=async()=>{try{setItems(await api.getAlerts())}catch(e){notify(e.message,"error")}}; useEffect(()=>{load()},[]);
 const act=async(fn,msg)=>{try{await fn();await load();notify(msg)}catch(e){notify(e.message,"error")}};
 return <div><div className="page-heading"><div><div className="eyebrow">EVENT CENTER</div><h1>Alerts</h1><p>Prioritized events generated by simulated telemetry and operations.</p></div><button className="secondary-btn" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
 <div className="panel"><div className="table-wrap"><table><thead><tr><th>Alert</th><th>Bin</th><th>Type</th><th>Severity</th><th>Created</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(a=><tr key={a.alert_id}><td><b>{a.alert_id}</b></td><td>{a.bin_id}</td><td>{a.type}</td><td><StatusBadge status={a.severity}/></td><td>{new Date(a.created_at).toLocaleString()}</td><td>{a.status}</td><td><div className="row-actions"><button className="tiny-btn" onClick={()=>act(()=>api.acknowledgeAlert(a.alert_id),"Alert acknowledged")}><Check size={14}/> Acknowledge</button><button className="tiny-btn" onClick={()=>act(()=>api.assignAlert(a.alert_id),"Collection task assigned")}><ClipboardCheck size={14}/> Assign</button><button className="tiny-btn" onClick={()=>act(()=>api.resolveAlert(a.alert_id),"Alert resolved")}>Resolve</button></div></td></tr>)}</tbody></table></div></div></div>
}
